"""Generate assets/ui/themes.rcss from one semantic token table per theme.

RCSS has no custom properties, so every colour rule is written out once per theme. Editing the
tokens here and re-running keeps the dark, light and projector palettes structurally identical:
every rule exists in every theme, and only the token values differ.

Usage: python scripts/generate_ui_themes.py
"""
import pathlib

THEMES = {
    'workbench_dark': {
        'app': '#121418', 'chrome': '#181b20', 'surface': '#1b1e24', 'raised': '#23272f', 'sunken': '#121419', 'field': '#121419',
        'status': '#14171ce6', 'hover': '#ffffff12', 'pressed': '#ffffff1f', 'segment': '#5a6475',
        'border': '#ffffff17', 'border_strong': '#ffffff2b', 'separator': '#ffffff12',
        'text': '#e9ecf1', 'text2': '#a9b1bd', 'text3': '#8e97a5',
        'accent': '#6aa5ff', 'accent_bg': '#2f6fdf', 'accent_hover': '#2862d0', 'accent_text': '#ffffff',
        'accent_tint': '#5b9dff2e', 'accent_tint_text': '#b4d2ff', 'focus': '#dce9ff', 'focus_primary': '#ffffff',
        'success': '#4cc38a', 'warning': '#e5b256', 'danger': '#f26b70', 'info': '#6aa8ff',
        'success_tint': '#4cc38a24', 'warning_tint': '#e5b25626', 'danger_tint': '#f26b7026', 'info_tint': '#6aa8ff24',
        'success_text': '#7fdcac', 'warning_text': '#f0c97a', 'danger_text': '#ff9a9d', 'info_text': '#a3c9ff',
        'switch_off': '#ffffff5c', 'knob': '#ffffff', 'scroll': '#ffffff4d', 'scroll_hover': '#ffffff6b',
        'tooltip': '#0b0d10f2', 'tooltip_text': '#f3f5f8', 'tooltip_key': '#9aa3b0', 'scrim': '#0000006b',
        'meter': '#ffffff1a',
        'secondary': '#ffffff10', 'secondary_hover': '#ffffff1e', 'caption': '#1c1f26f7',
        'control_border': '#ffffff5c', 'control_border_hover': '#ffffff85', 'shadow': '#00000026',
        'disabled': '#5f6672', 'secondary_border': '#00000000', 'segment_text': '#f3f5f8', 'segment_icon': '#b4d2ff', 'segment_border': '#00000000',
        'plot_1': '#4f94ef', 'plot_2': '#e0702f', 'plot_3': '#1fae7c', 'plot_guide': '#ffffff1f',
        'brand_block': '#f47d24', 'brand_rim': '#c2410c', 'brand_paper': '#eef1f5', 'brand_ink': '#15181d',
        'window_close': '#c42b1c', 'window_close_pressed': '#c42b1ce6', 'window_close_text': '#ffffff', 'window_close_text_pressed': '#ffffffb3',
    },
    'workbench_light': {
        'app': '#eceef2', 'chrome': '#f6f7f9', 'surface': '#ffffff', 'raised': '#ffffff', 'sunken': '#eff1f4', 'field': '#ffffff',
        'status': '#f6f7f9eb', 'hover': '#0f172a0d', 'pressed': '#0f172a1a', 'segment': '#ffffff',
        'border': '#0f172a1f', 'border_strong': '#0f172a38', 'separator': '#0f172a14',
        'text': '#15181d', 'text2': '#4a5260', 'text3': '#5c6573',
        'accent': '#2563eb', 'accent_bg': '#2563eb', 'accent_hover': '#1d4ed8', 'accent_text': '#ffffff',
        'accent_tint': '#2563eb2e', 'accent_tint_text': '#1a46b8', 'focus': '#1d4ed8', 'focus_primary': '#1d4ed8',
        'success': '#15803d', 'warning': '#b45309', 'danger': '#dc2626', 'info': '#2563eb',
        'success_tint': '#15803d1a', 'warning_tint': '#b453091f', 'danger_tint': '#dc26261a', 'info_tint': '#2563eb1a',
        'success_text': '#11652f', 'warning_text': '#8f4206', 'danger_text': '#b11d1d', 'info_text': '#1d4ed8',
        'switch_off': '#0f172a73', 'knob': '#ffffff', 'scroll': '#0f172a66', 'scroll_hover': '#0f172a8c',
        'tooltip': '#1d2026f2', 'tooltip_text': '#f5f6f8', 'tooltip_key': '#aab1bb', 'scrim': '#0f172a40',
        'meter': '#0f172a14',
        'secondary': '#0f172a10', 'secondary_hover': '#0f172a1a', 'caption': '#fffffff7',
        'control_border': '#0f172a73', 'control_border_hover': '#0f172aa6', 'shadow': '#0f172a0f',
        'disabled': '#9aa1ab', 'secondary_border': '#0f172a2e', 'segment_text': '#15181d', 'segment_icon': '#2563eb', 'segment_border': '#0f172a80',
        'plot_1': '#2563eb', 'plot_2': '#e0620e', 'plot_3': '#0f9b6c', 'plot_guide': '#0f172a24',
        'brand_block': '#f47d24', 'brand_rim': '#c2410c', 'brand_paper': '#eef1f5', 'brand_ink': '#15181d',
        'window_close': '#c42b1c', 'window_close_pressed': '#c42b1ce6', 'window_close_text': '#ffffff', 'window_close_text_pressed': '#ffffffb3',
    },
    'workbench_projector': {
        'app': '#ffffff', 'chrome': '#f2f3f5', 'surface': '#ffffff', 'raised': '#ffffff', 'sunken': '#eceef1', 'field': '#ffffff',
        'status': '#f2f3f5f2', 'hover': '#0000001a', 'pressed': '#0000002e', 'segment': '#003ea8',
        'border': '#0000004d', 'border_strong': '#000000a6', 'separator': '#00000038',
        'text': '#000000', 'text2': '#1c2027', 'text3': '#2d333c',
        'accent': '#003ea8', 'accent_bg': '#003ea8', 'accent_hover': '#00327f', 'accent_text': '#ffffff',
        'accent_tint': '#003ea826', 'accent_tint_text': '#002a72', 'focus': '#b33f00', 'focus_primary': '#b33f00',
        'success': '#0b6b2e', 'warning': '#8a4a00', 'danger': '#b3001b', 'info': '#003ea8',
        'success_tint': '#0b6b2e21', 'warning_tint': '#8a4a0021', 'danger_tint': '#b3001b1c', 'info_tint': '#003ea81c',
        'success_text': '#07551f', 'warning_text': '#6b3900', 'danger_text': '#8f0015', 'info_text': '#002f80',
        'switch_off': '#00000080', 'knob': '#ffffff', 'scroll': '#00000080', 'scroll_hover': '#000000a6',
        'tooltip': '#000000', 'tooltip_text': '#ffffff', 'tooltip_key': '#c9ced6', 'scrim': '#00000040',
        'meter': '#0000001f',
        'secondary': '#00000012', 'secondary_hover': '#00000024', 'caption': '#ffffff',
        'control_border': '#00000080', 'control_border_hover': '#000000b3', 'shadow': '#00000012',
        'disabled': '#8a8f96', 'secondary_border': '#00000059', 'segment_text': '#ffffff', 'segment_icon': '#ffffff', 'segment_border': '#003ea8',
        'plot_1': '#1d5fd6', 'plot_2': '#c85000', 'plot_3': '#00845a', 'plot_guide': '#00000040',
        'brand_block': '#f47d24', 'brand_rim': '#c2410c', 'brand_paper': '#eef1f5', 'brand_ink': '#15181d',
        'window_close': '#b3001b', 'window_close_pressed': '#b3001be6', 'window_close_text': '#ffffff', 'window_close_text_pressed': '#ffffffb3',
    },
}

# Each rule is "selector": "property: token; property: token". Tokens are replaced per theme.
RULES = [
    ('body', 'background-color: transparent; color: text'),
    ('.command-bar, .draw-bar, .present-strip', 'background-color: chrome; border-color: separator'),
    ('.command-bar', 'border-bottom-width: 1dp'),
    ('.draw-bar', 'border-bottom-width: 1dp'),
    ('.present-strip', 'border-bottom-width: 1dp'),
    # As the window's own title bar, one surface spans the window under the strip's content.
    ('.title-bar', 'background-color: chrome; border-color: separator'),
    ('.title-bar', 'border-bottom-width: 1dp'),
    ('.window-title-bar .command-bar, .window-title-bar .present-strip', 'background-color: transparent; border-bottom-width: 0dp'),
    # The app icon keeps its own colours in every theme.
    ('.window-mark-block', 'background-color: brand_block; border-color: brand_rim'),
    ('.window-mark-rim-right, .window-mark-rim-left', 'background-color: brand_rim'),
    ('.window-mark-com', 'background-color: brand_paper'),
    ('.window-mark-com-a, .window-mark-com-b', 'background-color: brand_ink'),
    ('.window-divider', 'background-color: border'),
    ('.window-control', 'background-color: transparent; color: text2'),
    # An inactive window dims its title and controls the way native title bars do.
    ('.window-inactive .window-control', 'color: disabled'),
    ('.window-inactive .command-bar .row-title, .window-inactive .present-strip .row-title', 'color: text2'),
    ('.window-control:hover, .window-control.is-hot', 'background-color: hover; color: text'),
    ('.window-control:active, .window-control.is-pressed', 'background-color: pressed; color: text'),
    ('.window-close:hover, .window-close.is-hot', 'background-color: window_close; color: window_close_text'),
    ('.window-close:active, .window-close.is-pressed', 'background-color: window_close_pressed; color: window_close_text_pressed'),
    # A fixed-size window's maximize button is greyed out, as a native one is.
    ('.window-control.is-disabled, .window-control.is-disabled:hover, .window-control.is-disabled:active', 'background-color: transparent; color: disabled'),
    ('.status-line', 'background-color: status; border-color: separator; color: text2'),
    ('.guide, .inspector, .measure', 'background-color: surface; border-color: separator'),
    ('.rail', 'background-color: chrome; border-color: separator'),
    ('.rail-expand', 'background-color: transparent; color: text2; border-color: transparent'),
    ('.rail-expand:hover', 'background-color: hover; color: text'),
    ('.rail-expand:active', 'background-color: pressed'),
    ('.rail-label', 'color: text2'),
    # The narrow window's Guide ribbon is a control, so it reads at full contrast.
    ('.rail-horizontal .rail-label, .rail-horizontal .rail-chevron', 'color: text'),
    ('.scrim', 'background-color: scrim'),

    ('.row-title', 'color: text'),
    ('.row-heading', 'color: text3'),
    ('.row-label', 'color: text2'),
    ('.row-paragraph', 'color: text'),
    ('.row-separator', 'background-color: separator'),
    ('.name, .row-readout .name', 'color: text2'),
    ('.value, .row-readout .value', 'color: text'),
    ('.row-readout.tone-muted .value', 'color: text2'),
    ('.row-readout.tone-positive .value', 'color: success_text'),
    ('.row-readout.tone-warning .value', 'color: warning_text'),
    ('.row-readout.tone-danger .value', 'color: danger_text'),
    ('.row-readout.tone-info .value', 'color: info_text'),
    ('.row-value.is-flash, .row-readout.is-flash', 'background-color: accent_tint'),

    ('button.row', 'background-color: transparent; color: text; border-color: transparent'),
    ('button.row .icon', 'color: text2'),
    ('button.row .shortcut', 'color: text3'),
    ('button.row:hover', 'background-color: hover'),
    ('button.row:hover .icon', 'color: text'),
    ('button.row:active', 'background-color: pressed'),
    ('button.row.selected, button.row.is-selected', 'background-color: accent_tint; color: accent_tint_text'),
    ('button.row.selected .icon, button.row.is-selected .icon', 'color: accent_tint_text'),
    ('button.row.is-primary', 'background-color: accent_bg; color: accent_text'),
    ('button.row.is-primary .icon', 'color: accent_text'),
    ('button.row.is-primary:hover', 'background-color: accent_hover'),
    ('button.row.is-primary:active', 'background-color: accent_bg'),
    ('button.row .badge', 'background-color: accent_bg; color: accent_text'),
    ('button.row.is-primary.is-disabled, button.row.is-primary.is-disabled:hover', 'background-color: secondary; color: disabled'),
    ('button.row.is-primary.is-disabled .icon', 'color: disabled'),
    ('button.row.is-disabled, button.row.is-disabled:hover', 'background-color: transparent; color: disabled'),
    ('button.row.is-disabled .icon', 'color: disabled'),
    ('button.row.is-disabled .switch-label', 'color: disabled'),
    ('button.row:focus-visible, .segment:focus-visible, .rail-expand:focus-visible, .stepper-button:focus-visible, .checklist-summary:focus-visible, .checklist-option:focus-visible, .notice-action:focus-visible, .toast-action:focus-visible, .toast-dismiss:focus-visible', 'border-color: focus'),
    ('button.row.is-primary:focus-visible', 'border-color: focus_primary'),
    ('button.row-section', 'color: text3; border-top-color: separator'),
    ('button.row-section:hover', 'background-color: transparent; color: text'),
    ('button.row-section .icon', 'color: text3'),
    ('button.row-list_item.selected, button.row-list_item.is-selected', 'background-color: accent_tint; color: text'),
    ('button.row.is-danger, button.row.is-danger .icon', 'color: danger_text'),
    ('button.row.is-danger:hover', 'background-color: danger_tint'),
    ('button.row.is-quiet', 'color: text2'),
    ('.guide button.row-action, .inspector button.row-action, .measure button.row-action, .sheets button.row-action, .hint button.row-action', 'background-color: secondary; border-color: secondary_border'),
    ('.guide button.row-action:focus-visible, .inspector button.row-action:focus-visible, .measure button.row-action:focus-visible, .sheets button.row-action:focus-visible, .hint button.row-action:focus-visible', 'border-color: focus'),
    ('.guide button.row-action:hover, .inspector button.row-action:hover, .measure button.row-action:hover, .sheets button.row-action:hover, .hint button.row-action:hover', 'background-color: secondary_hover'),
    ('.guide button.row-action:active, .inspector button.row-action:active, .measure button.row-action:active, .sheets button.row-action:active, .hint button.row-action:active', 'background-color: pressed'),
    ('.guide button.row-action.is-primary, .inspector button.row-action.is-primary, .measure button.row-action.is-primary, .sheets button.row-action.is-primary, .hint button.row-action.is-primary', 'background-color: accent_bg; color: accent_text'),
    ('.guide button.row-action.is-primary:hover, .inspector button.row-action.is-primary:hover, .measure button.row-action.is-primary:hover, .sheets button.row-action.is-primary:hover, .hint button.row-action.is-primary:hover', 'background-color: accent_hover'),
    ('.guide button.row-action.is-quiet, .inspector button.row-action.is-quiet, .measure button.row-action.is-quiet, .sheets button.row-action.is-quiet, .hint button.row-action.is-quiet, .guide button.row-action.header-action, .inspector button.row-action.header-action, .measure button.row-action.header-action, .sheets button.row-action.header-action, .hint button.row-action.header-action', 'background-color: transparent; border-color: transparent'),
    ('.guide button.row-action.is-quiet:focus-visible, .inspector button.row-action.is-quiet:focus-visible, .measure button.row-action.is-quiet:focus-visible, .sheets button.row-action.is-quiet:focus-visible, .hint button.row-action.is-quiet:focus-visible, .guide button.row-action.header-action:focus-visible, .inspector button.row-action.header-action:focus-visible, .measure button.row-action.header-action:focus-visible, .sheets button.row-action.header-action:focus-visible, .hint button.row-action.header-action:focus-visible', 'border-color: focus'),
    ('.guide button.row-action.is-quiet:hover, .inspector button.row-action.is-quiet:hover, .measure button.row-action.is-quiet:hover, .sheets button.row-action.is-quiet:hover, .hint button.row-action.is-quiet:hover, .guide button.row-action.header-action:hover, .inspector button.row-action.header-action:hover, .measure button.row-action.header-action:hover, .sheets button.row-action.header-action:hover, .hint button.row-action.header-action:hover', 'background-color: hover'),
    ('.guide button.row-action.is-danger:hover, .inspector button.row-action.is-danger:hover, .measure button.row-action.is-danger:hover, .sheets button.row-action.is-danger:hover, .hint button.row-action.is-danger:hover', 'background-color: danger_tint'),
    ('.guide button.row-action.selected, .inspector button.row-action.selected, .measure button.row-action.selected, .sheets button.row-action.selected, .hint button.row-action.selected', 'background-color: accent_tint; color: accent_tint_text; border-color: transparent'),
    ('.row-label.group-concepts', 'background-color: hover; color: text2'),
    ('.meter-value', 'color: text'),
    ('.row-heading.group-object_name', 'color: text'),
    ('.guide button.row-checkbox .checkbox-label', 'color: text'),
    ('.guide button.row-checkbox.is-on .checkbox-label', 'color: text2'),
    ('.measure .row-readout.is-primary', 'border-color: border'),
    ('.measure-grip-pill', 'background-color: scroll'),
    ('.measure-grip:hover .measure-grip-pill, .measure-grip.is-dragging .measure-grip-pill', 'background-color: accent'),
    ('#panel-shortcuts .row-readout .value', 'background-color: sunken; border-color: border; color: text2'),
    ('.sheets button.row-action.group-results', 'background-color: transparent'),
    ('.sheets button.row-action.group-results:hover', 'background-color: hover'),
    ('.sheets button.row-action.group-results.is-selected', 'background-color: accent_tint; color: accent_tint_text'),
    ('.list-title', 'color: text'),
    ('.list-secondary', 'color: text2'),
    ('.list-badges', 'color: text3'),
    ('button.row-list_item.selected .list-badges, button.row-list_item.is-selected .list-badges', 'color: text2'),

    ('.control-label, .switch-label, .checkbox-label', 'color: text2'),
    ('.control-hint, .control-range, .editing-tag, .unit', 'color: text3'),
    ('.number-field, .select, .text-field, .checklist-summary', 'background-color: field; color: text; border-color: control_border'),
    ('.field-placeholder, .field-icon', 'color: text3'),
    ('.row-select.is-mixed selectvalue', 'color: text2'),
    ('.number-field:hover, .select:hover, .text-field:hover, .checklist-summary:hover', 'border-color: control_border_hover'),
    ('.number-field:focus, .text-field:focus, .select:focus', 'border-color: focus'),
    ('.number-field.is-invalid', 'border-color: danger'),
    ('.field-error', 'color: danger_text'),
    ('select selectbox', 'background-color: raised; border-color: border; color: text'),
    ('select selectarrow', 'border-color: text2'),
    ('.checklist-chevron', 'border-color: text2'),
    ('select selectbox option:hover, select selectbox option:checked', 'background-color: hover'),
    ('.segmented', 'background-color: sunken; border-color: border'),
    ('.segment', 'background-color: transparent; color: text2; border-color: transparent'),
    ('.segment .icon', 'color: text2'),
    ('.segment:hover', 'color: text'),
    ('.segment.is-selected, .segment.selected', 'background-color: segment; color: segment_text; border-color: segment_border'),
    ('.segment.is-selected .icon, .segment.selected .icon', 'color: segment_icon'),
    ('.segment.is-selected:focus-visible, .segment.selected:focus-visible', 'border-color: focus'),
    # An unavailable choice keeps showing its value, greyed like an unavailable button.
    ('.row-segmented.is-disabled .segment, .row-segmented.is-disabled .segment:hover', 'color: disabled'),
    ('.row-segmented.is-disabled .segment .icon', 'color: disabled'),
    ('.row-segmented.is-disabled .segment.is-selected, .row-segmented.is-disabled .segment.selected', 'background-color: secondary; color: disabled; border-color: transparent'),
    ('.row-segmented.is-disabled .segment.is-selected .icon, .row-segmented.is-disabled .segment.selected .icon', 'color: disabled'),
    ('.radio-list .segment', 'color: text'),
    ('.radio-list .segment:hover', 'background-color: hover'),
    # A chosen radio row is marked by its filled ring and tint; a segment's outline would read as focus.
    ('.radio-list .segment.is-selected', 'background-color: accent_tint; border-color: transparent'),
    ('.radio-list .segment.is-selected:focus-visible', 'border-color: focus'),
    ('.radio-mark', 'border-color: text3'),
    ('.radio-list .segment.is-selected .radio-mark', 'border-color: accent; background-color: accent'),
    ('.tabs', 'border-bottom-color: separator'),
    ('.tabs .segment, .tabs .segment:hover', 'background-color: transparent; border-bottom-color: transparent'),
    ('.tabs .segment.is-selected', 'background-color: transparent; color: text; border-color: transparent; border-bottom-color: accent'),
    ('.tabs .segment:focus-visible', 'border-color: focus'),
    ('#legacy-inspector-target .tabs', 'background-color: sunken; border-color: border'),
    ('#legacy-inspector-target .tabs .segment, #legacy-inspector-target .tabs .segment:hover', 'background-color: transparent; color: text2; border-color: transparent'),
    ('#legacy-inspector-target .tabs .segment:hover', 'color: text'),
    ('#legacy-inspector-target .tabs .segment.is-selected', 'background-color: segment; color: segment_text; border-color: segment_border'),
    ('#legacy-inspector-target .tabs .segment:focus-visible', 'border-color: focus'),
    ('.switch-track', 'background-color: switch_off'),
    ('.switch-track.is-on', 'background-color: accent_bg'),
    ('.switch-knob', 'background-color: knob'),
    ('.checkbox-box', 'border-color: text3; color: accent_text'),
    ('button.row-checkbox.is-on .checkbox-box', 'background-color: accent_bg; border-color: accent_bg'),
    ('.stepper-button, .notice-action, .toast-action', 'background-color: transparent; color: text; border-color: border_strong'),
    ('.stepper-button', 'border-color: control_border'),
    ('.stepper-button:hover, .notice-action:hover, .toast-action:hover', 'background-color: hover'),
    ('.checklist-menu', 'background-color: raised; border-color: border'),
    ('.checklist-option', 'background-color: transparent; color: text; border-color: transparent'),
    ('.checklist-option:hover', 'background-color: hover'),
    ('.checklist-option.is-selected', 'background-color: accent_tint; color: accent_tint_text'),
    ('.dial', 'border-color: border_strong'),
    ('.meter', 'background-color: meter'),
    ('.slider slidertrack', 'background-color: switch_off'),
    ('.slider sliderbar', 'background-color: knob; border-color: control_border'),
    ('.slider sliderbar:hover, .slider sliderbar:active', 'background-color: knob; border-color: accent'),
    ('.meter div', 'background-color: accent'),
    # Energy share bars take the colour of the matching plot series.
    ('.meter.series-1 div', 'background-color: plot_1'),
    ('.meter.series-2 div', 'background-color: plot_2'),
    ('.meter.series-3 div', 'background-color: plot_3'),
    ('.row-notice', 'background-color: info_tint; border-left-color: info; color: text'),
    ('.row-notice.tone-warning', 'background-color: warning_tint; border-left-color: warning'),
    ('.row-notice.tone-danger', 'background-color: danger_tint; border-left-color: danger'),
    ('.row-notice.tone-positive', 'background-color: success_tint; border-left-color: success'),
    # Plot canvas parts: the plot element reads these computed colours when it draws.
    ('.plot-canvas', 'background-color: sunken; border-color: separator'),
    ('.plot-caption, .plot-key, .plot-tooltip-muted, .plot-neutral, .plot-empty', 'color: text2'),
    ('.plot-tick, .plot-marker, .plot-cursor, .plot-empty-detail, .plot-icon', 'color: text3'),
    ('.plot-grid', 'color: separator'),
    ('.plot-baseline', 'color: border_strong'),
    ('.plot-impact', 'color: plot_guide'),
    ('.plot-series-1', 'color: plot_1'),
    ('.plot-series-2', 'color: plot_2'),
    ('.plot-series-3', 'color: plot_3'),
    ('.plot-cursor-pinned', 'color: accent'),
    ('.plot-tooltip', 'background-color: raised; border-color: border_strong; color: text'),
    ('.plot-shadow', 'color: scrim'),
    ('.plot-limit', 'color: text2'),
    ('.plot-operating', 'color: accent'),

    ('.command-bar .row-title, .present-strip .row-title', 'color: text'),
    ('.command-bar .row-readout .value', 'background-color: hover; color: text2'),
    ('.command-bar .row-readout.tone-positive .value', 'background-color: success_tint; color: success_text'),
    ('.command-bar .row-readout.tone-info .value', 'background-color: info_tint; color: info_text'),
    ('.command-bar .row-readout.tone-warning .value', 'background-color: warning_tint; color: warning_text'),
    ('.command-bar .row-readout.tone-danger .value', 'background-color: danger_tint; color: danger_text'),
    ('.command-bar button.row.selected, .draw-bar button.row.selected, .present-strip button.row.selected', 'border-bottom-color: accent'),
    ('.command-bar button.row.selected:focus-visible, .draw-bar button.row.selected:focus-visible, .present-strip button.row.selected:focus-visible', 'border-color: focus'),
    ('.status-line .row-readout .value', 'color: text2'),
    ('.status-line .row-readout.tone-info .value', 'color: info_text'),
    ('.status-line button.row', 'color: text2'),
    ('.status-line button.row.selected, .status-line button.row.is-selected', 'background-color: warning_tint; color: warning_text'),
    ('.status-line button.row.selected .icon, .status-line button.row.is-selected .icon', 'color: warning_text'),
    ('.present-strip .row-readout .icon', 'color: text2'),
    ('.draw-bar .row-readout .icon', 'color: text2'),
    ('.draw-bar .row-readout.tone-warning .icon, .draw-bar .row-readout.tone-warning .value', 'color: warning_text'),
    ('.present-caption .panel', 'background-color: caption; border-color: border'),
    ('.present-caption .row-label.group-caption_header', 'color: text3'),
    ('.present-caption .row-paragraph', 'color: text'),
    ('.present-caption .row-label.group-caption_notice', 'color: text2; border-top-color: separator'),
    ('.present-caption button.row', 'background-color: secondary'),
    ('.present-caption button.row:hover', 'background-color: secondary_hover'),
    ('.present-caption button.row.is-primary', 'background-color: accent_bg; color: accent_text'),
    ('.present-caption button.row.is-primary:hover', 'background-color: accent_hover'),
    ('.present-caption button.row.is-quiet', 'background-color: transparent; color: text2'),
    ('.present-caption button.row.is-disabled, .present-caption button.row.is-disabled:hover', 'background-color: transparent; color: disabled'),
    ('.present-caption button.row.is-disabled .icon', 'color: disabled'),

    ('.popovers', 'background-color: raised; border-color: border_strong'),
    ('.shadow-layer div', 'background-color: shadow'),
    ('.popovers .menu-overflow', 'border-bottom-color: separator'),
    ('.popovers .row-title', 'color: text'),
    ('.sheets .panel', 'background-color: raised; border-color: border'),
    ('.hint .panel', 'background-color: raised; border-color: border'),
    ('.banner .row-notice', 'background-color: raised; border-color: border; color: text'),
    ('.toast', 'background-color: raised; border-color: border; border-left-color: info; color: text'),
    ('.toast.error', 'border-left-color: danger'),
    ('.toast.warning', 'border-left-color: warning'),
    ('.toast.success', 'border-left-color: success'),
    ('.toast-dismiss', 'background-color: transparent; color: text3; border-color: transparent'),
    ('.toast-dismiss:hover', 'background-color: hover; color: text'),
    ('.tooltip', 'background-color: tooltip; color: tooltip_text'),
    ('.tooltip-key', 'color: tooltip_key'),
    ('.status-chip', 'background-color: hover; color: text'),
    ('scrollbarvertical slidertrack', 'background-color: transparent'),
    ('scrollbarvertical sliderbar', 'background-color: scroll'),
    ('scrollbarvertical sliderbar:hover, scrollbarvertical sliderbar:active', 'background-color: scroll_hover'),
]


def render():
    lines = ['/* Generated by scripts/generate_ui_themes.py from semantic theme tokens. Edit the tokens',
             '   there and re-run; activated through RmlUi Context::ActivateTheme. */']
    for theme, tokens in THEMES.items():
        lines.append('@media (theme: %s) {' % theme)
        for selector, declarations in RULES:
            parts = []
            for declaration in declarations.split(';'):
                name, value = (item.strip() for item in declaration.split(':', 1))
                value = '#00000000' if value == 'transparent' else tokens.get(value, value)
                parts.append('%s: %s;' % (name, value))
            lines.append('  %s { %s }' % (selector, ' '.join(parts)))
        lines.append('}')
    return '\n'.join(lines) + '\n'


if __name__ == '__main__':
    target = pathlib.Path(__file__).resolve().parent.parent / 'assets' / 'ui' / 'themes.rcss'
    target.write_text(render(), encoding='utf-8', newline='\n')
    print('wrote', target)
